ReportAspNetCore/Models/ErrorViewModel.cs
using System;

namespace ReportAspNetCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ReportAspNetCore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Data;
using Microsoft.AspNetCore.Mvc;
using Models;
using ReportAspNetCore.Models;

namespace ReportAspNetCore.Controllers
{
    [Route("Home")]
    public class HomeController : Controller
    {
        private readonly DatabaseContext _databaseContext;

        public HomeController(DatabaseContext DatabaseContext)
        {
            _databaseContext = DatabaseContext;
        }
        
        [Route("")]
        [Route("Index")]
        [Route("~/")]
        [HttpGet]
        public IActionResult Index()
        {
            var displaydata = _databaseContext.GetDatas.ToList();

            return View(displaydata);
        }

        [Route("Index")]
        [HttpPost]
        public async Task<IActionResult> Index(GetData data)
        {

            if (ModelState.IsValid)
            {
                _databaseContext.Add(data);
                await _databaseContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(data);
        }

        [Route("GetNameByCode")]
        public IActionResult GetNameByCode(string code) 
        {
            var datalist = _databaseContext.GetNames.Where(u => u.Code == code).ToList();

            return new JsonResult(datalist);
        }
    }
}

ReportAspNetCore/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReportAspNetCore.Models;
using Stimulsoft.Base;
using Stimulsoft.Report;
using Stimulsoft.Report.Mvc;

namespace ReportAspNetCore.Controllers
{
    public class PeopleController : Controller
    {
        private readonly Data.DatabaseContext _context;

        public PeopleController(Data.DatabaseContext context)
        {
            _context = context;
            StiLicense.LoadFromString("6vJhGtLLLz2GNviWmUTrhSqnOItdDwjBylQzQcAOiHl2AD0gPVknKsaW0un+3PuM6TTcPMUAWEURKXNso0e5OJN40hxJjK5JbrxU+NrJ3E0OUAve6MDSIxK3504G4vSTqZezogz9ehm+xS8zUyh3tFhCWSvIoPFEEuqZTyO744uk+ezyGDj7C5jJQQjndNuSYeM+UdsAZVREEuyNFHLm7gD9OuR2dWjf8ldIO6Goh3h52+uMZxbUNal/0uomgpx5NklQZwVfjTBOg0xKBLJqZTDKbdtUrnFeTZLQXPhrQA5D+hCvqsj+DE0n6uAvCB2kNOvqlDealr9mE3y978bJuoq1l4UNE3EzDk+UqlPo8KwL1XM+o1oxqZAZWsRmNv4Rr2EXqg/RNUQId47/4JO0ymIF5V4UMeQcPXs9DicCBJO2qz1Y+MIpmMDbSETtJWksDF5ns6+B0R7BsNPX+rw8nvVtKI1OTJ2GmcYBeRkIyCB7f8VefTSOkq5ZeZkI8loPcLsR4fC4TXjJu2loGgy4avJVXk32bt4FFp9ikWocI9OQ7CakMKyAF6Zx7dJF1nZw");
        }

        public IActionResult PrintPerson(int id)
        {
            return View();
        }

        // GET: People
        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.ToListAsync());
        }

        public IActionResult PrintPage()
        {
            return View("PrintPage");
        }

        public IActionResult Print()
        {
            StiReport report = new StiReport();
            report.Load(StiNetCoreHelper.MapPath(this, "wwwroot/Reports/Report.mrt"));
            var persons = _context.GetDatas.ToList();
            report.RegData("dt", persons);
            return StiNetCoreViewer.GetReportResult(this, report);
        }

        public IActionResult PrintPerople()
        {
            StiReport report = new StiReport();
            report.Load(StiNetCoreHelper.MapPath(this, "wwwroot/Reports/Report2.mrt"));
            var persons = _context.GetDatas.First();
            report.RegData("dt", persons);
            return StiNetCoreViewer.GetReportResult(this, report);
        }

        public IActionResult ViewerEvent()
        {
            return StiNetCoreViewer.ViewerEventResult(this);
        }
    }
}

ReportAspNetCore/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReportAspNetCore.Models;
using Stimulsoft.Base;
using Stimulsoft.Report;
using Stimulsoft.Report.Mvc;

namespace ReportAspNetCore.Controllers
{
    public class ReportController : Controller
    {
        private readonly Data.DatabaseContext _context;

        public ReportController(Data.DatabaseContext context)
        {
            _context = context;
            StiLicense.LoadFromString("6vJhGtLLLz2GNviWmUTrhSqnOItdDwjBylQzQcAOiHl2AD0gPVknKsaW0un+3PuM6TTcPMUAWEURKXNso0e5OJN40hxJjK5JbrxU+NrJ3E0OUAve6MDSIxK3504G4vSTqZezogz9ehm+xS8zUyh3tFhCWSvIoPFEEuqZTyO744uk+ezyGDj7C5jJQQjndNuSYeM+UdsAZVREEuyNFHLm7gD9OuR2dWjf8ldIO6Goh3h52+uMZxbUNal/0uomgpx5NklQZwVfjTBOg0xKBLJqZTDKbdtUrnFeTZLQXPhrQA5D+hCvqsj+DE0n6uAvCB2kNOvqlDealr9mE3y978bJuoq1l4UNE3EzDk+UqlPo8KwL1XM+o1oxqZAZWsRmNv4Rr2EXqg/RNUQId47/4JO0ymIF5V4UMeQcPXs9DicCBJO2qz1Y+MIpmMDbSETtJWksDF5ns6+B0R7BsNPX+rw8nvVtKI1OTJ2GmcYBeRkIyCB7f8VefTSOkq5ZeZkI8loPcLsR4fC4TXjJu2loGgy4avJVXk32bt4FFp9ikWocI9OQ7CakMKyAF6Zx7dJF1nZw");
        }

        public IActionResult PrintPerson(int id)
        {
            return View();
        }

        // GET: People
        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.ToListAsync());
        }

        public IActionResult PrintPage()
        {
            System.Globalization.PersianCalendar persianCalandar =
              new System.Globalization.PersianCalendar();

            int year = persianCalandar.GetYear(DateTime.Now);
            int month = persianCalandar.GetMonth(DateTime.Now);
            int day = persianCalandar.GetDayOfMonth(DateTime.Now);

            var datePersian = ($"{year}/{month}/{day}");


            var date = _context.GetDatas.ToArray();

            var select = _context.GetDatas.Select(c => c.Date.Substring(0, 2)).Distinct();

            ViewBag.Years = select;

            return View("PrintPage");
        }

        public IActionResult Print()
        {
            StiReport report = new StiReport();
            report.Load(StiNetCoreHelper.MapPath(this, "wwwroot/Reports/Report.mrt"));
            var persons = _context.GetDatas.ToList();
            report.RegData("dt", persons);
            return StiNetCoreViewer.GetReportResult(this, report);
        }

        public IActionResult PrintPerople()
        {
            StiReport report = new StiReport();
            report.Load(StiNetCoreHelper.MapPath(this, "wwwroot/Reports/Report2.mrt"));
            var persons = _context.GetDatas.First();
            report.RegData("dt", persons);
            return StiNetCoreViewer.GetReportResult(this, report);
        }

        public IActionResult ViewerEvent()
        {
            return StiNetCoreViewer.ViewerEventResult(this);
        }
    }
}

ReportAspNetCore/Views/Home/Index.cshtml
@model IEnumerable<Models.GetData>
@{
    Layout = "/Views/Shared/_Layout.cshtml";
}

<div class="rtl">


    <form asp-action="Index">
        <div class="input-container">
            <div class="input">
                <div>
                    <label for="Code" class="label">کد</label>
                    <input name="Code" type="text" id="codeInput" />
                </div>

                <div>
                    <label for="name" class="label">نام</label>
                    <input name="name" type="text" id="nameInput" />
                </div>

                <div>
                    <label for="Date" class="label">تاریخ</label>
                    <input name="Date" type="text" id="inputDate3" class="inputDate" aria-label="date3" aria-describedby="date3" />
                    <span class="spanDate material-icons md-24 input-group-lg" id="date3">calendar_today</span>
                </div>

                <div>
                    <label for="YearSeason" class="label">سال / فصل</label>
                    <input name="YearSeason" id="SetDate" type="text" onclick="Click(); convertNumber();" />

                </div>

                <div>
                    <label for="ContractNumber" class="label">شماره قرار داد</label>
                    <input name="ContractNumber" type="text" />
                </div>

                <div>
                    <label for="ContractCount" class="label">تعداد قرار داد</label>
                    <input name="ContractCount" type="text" />
                </div>

                <div>
                    <label for="NoContractCount" class="label">تعداد بدون قرار داد</label>
                    <input name="NoContractCount" type="text" />
                </div>

                <div>
                    <label for="NoContractCount" class="label">تعداد بدون قرار داد</label>
                    <input name="NoContractCount" type="text" />
                </div>

                <div>
                    <label for="InvoiceNumber" class="label">شماره فاکتور</label>
                    <input name="InvoiceNumber" type="text" />
                </div>

                <div>
                    <label for="Count" class="label">تعداد</label>
                    <input name="Count" id="Count" type="text" />
                </div>

                <div>
                    <label for="PerSale" class="label">فی فروش</label>
                    <input name="PerSale" id="PerSale" type="text" onkeyup="separateNum(this.value,this);" />
                </div>

                <div>
                    <label for="NetSales" class="label">خالص فروش</label>
                    <input name="NetSales" id="NetSales" type="text" onclick="Sales()" onkeyup="separateNum(this.value,this);" />
                </div>

                <div>
                    <label for="Discount" class="label">تخفیف</label>
                    <input name="Discount" id="Discount" type="text" onkeyup="separateNum(this.value,this);" />
                </div>

                <div>
                    <label for="SalesTax" class="label">فروش با ارزش افزوده</label>
                    <input name="SalesTax" id="SalesTax" type="text" onclick="Tax()" onkeyup="separateNum(this.value,this);" />
                </div>

                <div>
                    <label for="ReturnedCount" class="label">تعداد برگشت</label>
                    <input name="ReturnedCount" type="text" />
                </div>

                <div>
                    <label for="RefundAmount" class="label">مبلغ برگشت</label>
                    <input name="RefundAmount" type="text" onkeyup="separateNum(this.value,this);" />
                </div>

                <div>
                    <label for="ReceivedMoney" class="label">مبلغ دریافت</label>
                    <input name="ReceivedMoney" type="text" onkeyup="separateNum(this.value,this);" />
                </div>

                <div>
                    <label for=""></label>
                    <input type="submit" value="SUBMIT" />
                </div>

            </div>
        </div>
    </form>

    <br>
    <hr>
    <br>

    <div class="container mb-3">
        <table class="table table-striped table-border mydatatable" style="width: 100%;">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.Name)</th>
                    <th>@Html.DisplayNameFor(model => model.Date)</th>
                    <th>@Html.DisplayNameFor(model => model.Count)</th>
                    <th>@Html.DisplayNameFor(model => model.PerSale)</th>
                    <th>@Html.DisplayNameFor(model => model.SalesTax)</th>
                    <th>@Html.DisplayNameFor(model => model.ReceivedMoney)</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.Date)</td>
                        <td>@Html.DisplayFor(modelItem => item.Count)</td>
                        <td>@Html.DisplayFor(modelItem => item.PerSale)</td>
                        <td>@Html.DisplayFor(modelItem => item.SalesTax)</td>
                        <td>@Html.DisplayFor(modelItem => item.ReceivedMoney)</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

ReportAspNetCore/Views/Report/PrintPage.cshtml
@using Stimulsoft.Report.Mvc

@{
    ViewData["Title"] = "Print";
}

@foreach (var item in ViewBag.Years)
{
    <a type="button" class="btn btn-primary" href="#">@item</a>
}


@Html.StiNetCoreViewer(new StiNetCoreViewerOptions()
{
    Actions =
    {
        GetReport = "Print",
        ViewerEvent = "ViewerEvent"
    }
})

ReportAspNetCore/Views/Report/PrintPerson.cshtml
@using Stimulsoft.Report.Mvc

@{
    ViewData["Title"] = "PrintPerson";
}

@Html.StiNetCoreViewer(new StiNetCoreViewerOptions()
{
    Actions =
    {
        GetReport = "PrintPerople",
        ViewerEvent = "ViewerEvent"
    }
})

ReportAspNetCore/Views/Shared/_Layout.cshtml
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DataTable</title>

    <!-- Link  -->
    @* <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"> *@
    <link rel="stylesheet" href="~/lib/bootstrap-v4-rtl-master/dist/css/bootstrap-rtl.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/src/jquery.md.bootstrap.datetimepicker.style.css" />

    <link rel="stylesheet" href="~/css/style.css" />

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />

</head>

<body>

  <partial name="_navbarPartial" />


    <br>

    @RenderBody()

    <!-- Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
    
    <script src="~/src/jquery.md.bootstrap.datetimepicker.js"></script>
    <script src="~/js/script.js" asp-append-version="true" ></script>

    @RenderSection("Scripts", required: false)

</body>
</html>

ReportAspNetCore/Views/Shared/_datePartial.cshtml
@using System.Globalization

@{
    PersianCalendar persianCalendar = new PersianCalendar();

    string persianDate = persianCalendar.GetYear(DateTime.Now) + "/" +
                         persianCalendar.GetMonth(DateTime.Now).ToString("00") + "/"+
                         persianCalendar.GetDayOfMonth(DateTime.Now).ToString("00");
}

<a>@persianDate</a>

@*<partial name="_datePartial">*@

ReportAspNetCore/Views/Shared/_navbarPartial.cshtml
<div class="rtl">
    <nav class="navbar navbar-expand-sm navbar-light">
        <div id="mySidenav" class="sidenav">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        </div>
        <span class="menu" onclick="openNav()">&#9776;</span>
        <a class="navbar-brand" asp-controller="Home" asp-action="Index"> ثبت اطلاعات </a>
        <a class="navbar-brand" asp-controller="Report" asp-action="PrintPage">گزارش فروش</a>
    </nav>
</div>